AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'spec/**/*'
  TargetRubyVersion:                  2.7.1
Metrics/LineLength:
  Max:                                140
Style/Documentation:
  Enabled:                            false
Layout/ParameterAlignment:
  EnforcedStyle:                      with_fixed_indentation
Layout/MultilineMethodCallIndentation:
  EnforcedStyle:                      indented
Layout/MultilineHashBraceLayout:
  Enabled:                            false
Layout/EmptyLineAfterGuardClause:
  Enabled:                            false
Style/ClassAndModuleChildren:
  Enabled:                            false
Style/FrozenStringLiteralComment:
  Enabled:                            false
Style/EmptyMethod:
  EnforcedStyle:                      expanded
Metrics/MethodLength:
  Max:                                25
Metrics/CyclomaticComplexity:
  Max:                                10
Metrics/AbcSize:
  Max:                                40